version: "3"
services:
  app:
    container_name: containerize_app_1
    # your code goes here ...
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8000:8000"
  nginx:
    container_name: containerize_nginx_1
    # your code goes here ...
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/files:/etc/nginx/certs
    depends_on:
      - app
